### ISSUE TITLE
can't do "npm install" 

### ISSUE THREAD

**Issue by rizen** [mikro-orm/koa-ts-example-app#11]
npm install dies with:

```
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated formidable@1.2.2: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm ERR! code 1
npm ERR! path /private/tmp/mikroorm/koa-ts-example-app/node_modules/@vscode/sqlite3
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3360000/sqlite3.c
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.19.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp http GET https://nodejs.org/download/release/v16.19.0/node-v16.19.0-headers.tar.gz
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.19.0/node-v16.19.0-headers.tar.gz
npm ERR! gyp http GET https://nodejs.org/download/release/v16.19.0/SHASUMS256.txt
npm ERR! gyp http 200 https://nodejs.org/download/release/v16.19.0/SHASUMS256.txt
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/private/tmp/mikroorm/koa-ts-example-app/node_modules/@vscode/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jtsmith/Library/Caches/node-gyp/16.19.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/jtsmith/Library/Caches/node-gyp/16.19.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/jtsmith/Library/Caches/node-gyp/16.19.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/private/tmp/mikroorm/koa-ts-example-app/node_modules/@vscode/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! /bin/sh: python: command not found
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3360000/sqlite3.c] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.3.0
npm ERR! gyp ERR! command "/Users/jtsmith/.nvm/versions/node/v16.19.0/bin/node" "/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /private/tmp/mikroorm/koa-ts-example-app/node_modules/@vscode/sqlite3
npm ERR! gyp ERR! node -v v16.19.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jtsmith/.npm/_logs/2023-03-07T18_05_38_404Z-debug-0.log
```

**Comment by rizen** [comment]
This is with node v16.19.0 on an M2 Max Mac using MacOS 13.2

**Comment by rizen** [comment]
same problem with node v18.14.0

**Comment by B4nan** [comment]
Update the dependencies. Latest version of the sqlite driver is no longer using `@vscode/sqlite3` which is what fails to build.

**Comment by rizen** [comment]
It worked fine with v14.21.3, so it appears there must be a library conflict of some kind

**Comment by rizen** [comment]
Ah, hadn't seen your comment, but that makes sense.

**Comment by B4nan** [comment]
sqlite is using native libraries that are nodejs version dependent. If you switch nodejs version, you need to reinstall the npm deps.

**Comment by rizen** [comment]
In this case that doesn't really matter for me. I was simply trying for the past 3 days to get *anything* at all to work with mikro-orm. I've been copying and pasting from the various examples and straight up failing. 

But now that I got this repo working I finally figured out a bunch of totally non-obvious things (at least to me). 

So I'm reporting to you that "this example doesn't work as instructed in the Readme". So update the readme, or update the repo so it works out of the box, or do nothing. That's up to you. PS, the mikro-orm docs do a great job of showing what it is capable of and a terrible job of getting a novice like me started. If you would tell me where to submit it, I'd be happy to write up a complete idiot's guide to getting started with mikro-orm so other people wouldn't have to go through what I just did.

**Comment by B4nan** [comment]
I am quite sure this is about your environment, it works fine for me (and I am also on macos/m1). Will be happy to help, but please dont blame me for not being able to install third party dependencies like sqlite. 

This has nothing to do with what is in readme, the information there is correct.

**Comment by rizen** [comment]
Sorry if it came off as attempting to assign blame. That is not at all my goal.  That said, my environment is the latest version of MacOS with node installed. That's it. Nothing else. Then I simply git clone the repository, cd into it, and type `npm install`, and that's where it failed.  What beyond those steps should I have done?

**Comment by B4nan** [comment]
I'd blame the nodejs version switching, if it worked for you with v14 and started to fail afterwards. Have you tried to wipe node_modules? What about other example repositories? This one is apparently not set up to test via CI, but most of the others do, including renovate updates so new ORM releases are tested automatically on various nodejs versions.

**Comment by rizen** [comment]
I was on 16 to start. That's what went kablooey. I switched to 18, still kablooey. Switched to 14, that's when it actually worked. There wasn't a node_modules folder to wipe out when I first downloaded it. 


I just downloaded the whole thing again, and kept a complete history of everything I typed.

```
jtsmith@jts-MacBook-Pro ~ % cd /tmp 
jtsmith@jts-MacBook-Pro /tmp % mkdir test
jtsmith@jts-MacBook-Pro /tmp % pwd
/tmp
jtsmith@jts-MacBook-Pro /tmp % cd test 
jtsmith@jts-MacBook-Pro test % ls
jtsmith@jts-MacBook-Pro test % pwd
/tmp/test
jtsmith@jts-MacBook-Pro test % node -v
v16.19.0
jtsmith@jts-MacBook-Pro test % git clone git@github.com:mikro-orm/koa-ts-example-app.git
Cloning into 'koa-ts-example-app'...
remote: Enumerating objects: 66, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 66 (delta 34), reused 45 (delta 19), pack-reused 0
Receiving objects: 100% (66/66), 86.56 KiB | 791.00 KiB/s, done.
Resolving deltas: 100% (34/34), done.
jtsmith@jts-MacBook-Pro test % cd koa-ts-example-app 
jtsmith@jts-MacBook-Pro koa-ts-example-app % npm install
npm WARN deprecated ini@1.3.5: Please update to ini >=1.3.6 to avoid a prototype pollution issue
npm WARN deprecated fsevents@2.1.3: "Please update to latest v2.3 or v2.2"
npm WARN deprecated debug@3.2.6: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated formidable@1.2.2: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm ERR! code 1
npm ERR! path /private/tmp/test/koa-ts-example-app/node_modules/@vscode/sqlite3
npm ERR! command failed
npm ERR! command sh -c -- node-gyp rebuild
npm ERR! CC(target) Release/obj.target/nothing/../../node-addon-api/nothing.o
npm ERR!   LIBTOOL-STATIC Release/nothing.a
npm ERR!   ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3360000/sqlite3.c
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@9.1.0
npm ERR! gyp info using node@16.19.0 | darwin | arm64
npm ERR! gyp info find Python using Python version 3.9.6 found at "/Library/Developer/CommandLineTools/usr/bin/python3"
npm ERR! gyp info spawn /Library/Developer/CommandLineTools/usr/bin/python3
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   '/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'make',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/private/tmp/test/koa-ts-example-app/node_modules/@vscode/sqlite3/build/config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   '/Users/jtsmith/Library/Caches/node-gyp/16.19.0/include/node/common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=/Users/jtsmith/Library/Caches/node-gyp/16.19.0',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=/Users/jtsmith/Library/Caches/node-gyp/16.19.0/<(target_arch)/node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=/private/tmp/test/koa-ts-example-app/node_modules/@vscode/sqlite3',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn make
npm ERR! gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
npm ERR! warning: /Library/Developer/CommandLineTools/usr/bin/libtool: archive library: Release/nothing.a the table of contents is empty (no object file members in the library define global symbols)
npm ERR! /bin/sh: python: command not found
npm ERR! make: *** [Release/obj/gen/sqlite-autoconf-3360000/sqlite3.c] Error 127
npm ERR! gyp ERR! build error 
npm ERR! gyp ERR! stack Error: `make` failed with exit code: 2
npm ERR! gyp ERR! stack     at ChildProcess.onExit (/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:201:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm ERR! gyp ERR! System Darwin 22.3.0
npm ERR! gyp ERR! command "/Users/jtsmith/.nvm/versions/node/v16.19.0/bin/node" "/Users/jtsmith/.nvm/versions/node/v16.19.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm ERR! gyp ERR! cwd /private/tmp/test/koa-ts-example-app/node_modules/@vscode/sqlite3
npm ERR! gyp ERR! node -v v16.19.0
npm ERR! gyp ERR! node-gyp -v v9.1.0
npm ERR! gyp ERR! not ok

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/jtsmith/.npm/_logs/2023-03-07T20_33_21_677Z-debug-0.log
jtsmith@jts-MacBook-Pro koa-ts-example-app % 
```


I'm happy to provide you with any more information you may want if you want to try to fix this. However, I'm done with this repository now that I figured out what my problem was getting mikro to find my config file. So if you're just replying to help me troubleshoot we can be done here.

**Comment by piotr-cz** [comment]
Fixed with `npm update` instead of `npm install`.

Latest sqlite3 package releases [provide binaries](https://github.com/TryGhost/node-sqlite3/releases), so node-gyp doesn't have to build it and doesn't faill.

**Comment by B4nan** [comment]
updated the whole repo to v6 and latest for all dependencies, also switched to better-sqlite which has proper prebuilds
